export interface DogBreedOption {
  name_ko: string
  name_en: string
}

export const DOG_BREEDS: DogBreedOption[] = [
  { name_ko: '골든 리트리버', name_en: 'Golden Retriever' },
  { name_ko: '그레이트 피레니즈', name_en: 'Great Pyrenees' },
  { name_ko: '그레이하운드', name_en: 'Greyhound' },
  { name_ko: '꼬똥 드 툴레아', name_en: 'Coton de Tulear' },
  { name_ko: '닥스훈트', name_en: 'Dachshund' },
  { name_ko: '도베르만', name_en: 'Doberman Pinscher' },
  { name_ko: '두들', name_en: 'Doodle' },
  { name_ko: '라사압소', name_en: 'Lhasa Apso' },
  { name_ko: '말티즈', name_en: 'Maltese' },
  { name_ko: '미니어처 슈나우저', name_en: 'Miniature Schnauzer' },
  { name_ko: '미니어처 핀셔', name_en: 'Miniature Pinscher' },
  { name_ko: '믹스견', name_en: 'Mixed Breed' },
  { name_ko: '바센지', name_en: 'Basenji' },
  { name_ko: '바셋하운드', name_en: 'Basset Hound' },
  { name_ko: '버니즈 마운틴 독', name_en: 'Bernese Mountain Dog' },
  { name_ko: '베들링턴 테리어', name_en: 'Bedlington Terrier' },
  { name_ko: '보더콜리', name_en: 'Border Collie' },
  { name_ko: '보스턴 테리어', name_en: 'Boston Terrier' },
  { name_ko: '비글', name_en: 'Beagle' },
  { name_ko: '비숑 프리제', name_en: 'Bichon Frise' },
  { name_ko: '불독', name_en: 'Bulldog' },
  { name_ko: '불테리어', name_en: 'Bull Terrier' },
  { name_ko: '사모예드', name_en: 'Samoyed' },
  { name_ko: '삽살개', name_en: 'Sapsali' },
  { name_ko: '샤페이', name_en: 'Shar Pei' },
  { name_ko: '셰틀랜드 쉽독', name_en: 'Shetland Sheepdog' },
  { name_ko: '시바 이누', name_en: 'Shiba Inu' },
  { name_ko: '시츄', name_en: 'Shih Tzu' },
  { name_ko: '스코티시 테리어', name_en: 'Scottish Terrier' },
  { name_ko: '스피츠', name_en: 'Spitz' },
  { name_ko: '아메리칸 코커스패니얼', name_en: 'American Cocker Spaniel' },
  { name_ko: '아키타 이누', name_en: 'Akita' },
  { name_ko: '알래스칸 말라뮤트', name_en: 'Alaskan Malamute' },
  { name_ko: '요크셔테리어', name_en: 'Yorkshire Terrier' },
  { name_ko: '웰시코기', name_en: 'Welsh Corgi' },
  { name_ko: '이탈리안 그레이하운드', name_en: 'Italian Greyhound' },
  { name_ko: '잭 러셀 테리어', name_en: 'Jack Russell Terrier' },
  { name_ko: '재패니즈 친', name_en: 'Japanese Chin' },
  { name_ko: '저먼 셰퍼드', name_en: 'German Shepherd' },
  { name_ko: '진돗개', name_en: 'Jindo' },
  { name_ko: '차우차우', name_en: 'Chow Chow' },
  { name_ko: '치와와', name_en: 'Chihuahua' },
  { name_ko: '캐벌리어 킹 찰스 스패니얼', name_en: 'Cavalier King Charles Spaniel' },
  { name_ko: '코카스패니얼', name_en: 'Cocker Spaniel' },
  { name_ko: '페키니즈', name_en: 'Pekingese' },
  { name_ko: '포메라니안', name_en: 'Pomeranian' },
  { name_ko: '폼스키', name_en: 'Pomsky' },
  { name_ko: '푸들', name_en: 'Poodle' },
  { name_ko: '프렌치 불도그', name_en: 'French Bulldog' },
  { name_ko: '하바니즈', name_en: 'Havanese' },
  { name_ko: '화이트 테리어', name_en: 'West Highland White Terrier' },
  { name_ko: '휘핏', name_en: 'Whippet' },
  { name_ko: '기타', name_en: 'Other' },
]
